### ISSUE TITLE
Build out API for creating report sections, tiles, and trend graphs

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6236]
As part of the 3.0 development push, we're going to create a new API that allows core and extensions to easily create new report options.

Tracking PR | Project |
---------------- | -----------
| ~#6273~ | [3DD™: Reporting API Reboot](https://github.com/easydigitaldownloads/easy-digital-downloads/projects/2)

This API will comprise three primary pieces:

**Infrastructure**
* [x] #6253 – API to register (any) stuff
* [x] #6253 – API to handle exceptions
* [x] #6260 – Concrete class to initialize the Reports API

**Report (tabs)**
* [x] #6254 – API to register report tabs (PR: #6263)
* [x] #6284 – `Report` object (PR: #6289)
* [x] #6284  – API to build and render reports (PRs: #6289, #6329)
* [x] #6334 – Integrate the Carbon library to simplify date filtering (PR: #6353)
* [x] #6257 – API to register filters against report tabs (PR: #6361)
* [x] #6360 – Deprecate old report view/tab display actions using a callback (PR: #6371)
* [x] #6212 – Audit test coverage for Reports API Reboot pre-merge (PR: #6520)

**Endpoints**
* [x] #6280 – API for Endpoints (PR: #6283)
* [x] #6285 – Add tile support to the Endpoints API (PR: #6313)
* [x] #6287 – Add chart support to the Endpoints API
* [x] #6286 – Add table support to the Endpoints API (PR: #6339)
* [x] #6511 – Add pie chart support to the chart endpoint (PR: #6515)

**Nice to Have**
* [ ] #6281 – Expose endpoints via REST

The reports screen from AffiliateWP represents a fairly good view of what this API will ultimately provide:

![AffiliateWP Reports](https://user-images.githubusercontent.com/1034109/34129740-d4ea758e-e40a-11e7-8982-b3fc4855b764.png)

**Comment by DrewAPicture** [comment]
PR submitted to @mindctrl for review on #6253.

**Comment by DrewAPicture** [comment]
The empty `EDD_Reports` class has been merged to `issue/6236` via #6260. And so it goes.

**Comment by DrewAPicture** [comment]
It's worth noting that while we're in the process of moving the Logs tab from Reports to Tools, this tab largely comprises graphs that will (likely) be directly integrated into new Reports views, so may actually be able to just completely deprecate the Logs tab altogether at the end of this thing.

**Comment by DrewAPicture** [comment]
`EDD_Registry` was merged via #6253.

**Comment by DrewAPicture** [comment]
The Logs tab was moved to Tools in #6265.

**Comment by DrewAPicture** [comment]
Added PR for the master tracking issue (#6273). This is obviously going to be merged last, but all sub-issues are using `issue/6236` as a "master" branch, so this PR can be used to get a 10,000 ft view of progress on the Reports API reboot.

**Comment by DrewAPicture** [comment]
Decided to consolidate the effort between #6254 and #6255 into the PR for just #6254.

**Comment by DrewAPicture** [comment]
Added to-do items for the following:
* #6280 – Introduce an Endpoint API
* #6281 – Expose reports endpoints via REST
* #6284 – Create an API to build and render reports

The REST issue is still a maybe and lower priority than any of the others. But it would be nice to have.

**Comment by DrewAPicture** [comment]
Merged the Endpoint API in #6280.

**Comment by DrewAPicture** [comment]
Merged #6329 containing the bulk of the reports rendering logic for #6284.

**Comment by DrewAPicture** [comment]
Merged #6339 to add table endpoint support.

**Comment by DrewAPicture** [comment]
Integrated the `Carbon` library and introduced a variety of date functions and helpers in #6334.

**Comment by DrewAPicture** [comment]
Merged #6361. to introduce an API for registering and using filters.

**Comment by DrewAPicture** [comment]
Merged the PR for #6287 to introduce chart endpoint support.

**Comment by DrewAPicture** [comment]
#6515 was merged for #6511 to add pie chart endpoint support.

**Comment by DrewAPicture** [comment]
#6520 was merged for #6512 bringing this up to pretty much full test coverage!

**Comment by DrewAPicture** [comment]
The Reports API Reboot is now feature complete and ready for review! 🎉

**Comment by sunnyratilal** [comment]
@easydigitaldownloads/core-team Could we please have some testing done on this PR as it is pivotal for the next phase of 3DD where this new API will be extensively used.

@DrewAPicture has done phenomenal work here.

The Reports page now separates reports by vertical tabs.  Each report can consist of three endpoints: tiles, tables, and charts.

Please test with this example plugin that Drew created demonstrating how each of the three aforementioned endpoints will work (this will also provide a good example of how all the new APIs are used to create reports): https://gist.github.com/DrewAPicture/69acc0a74af184f11443687802ac89a4

There are two ways reports can be created using the new API: one is the using the way above and the other is by directly the functions: https://gist.github.com/DrewAPicture/d0717133deb5c1c7b569dfdbdd730676.  The first requires developers to wrap their code in a `try/catch`, the second does not.  However, both will still throw exceptions if invalid data is passed.

**To Test**
1. Check Reports page loads all of the existing EDD reports and displays existing charts
2. Install the [Example Report plugin](https://gist.github.com/DrewAPicture/69acc0a74af184f11443687802ac89a4) and ensure that the endpoints are displayed correctly.

**Note:**
Deprecated PHP notices are being thrown and this is intended.  These notices will begin to disappear once we recreate the reports using the new APIs.

**Comment by DrewAPicture** [comment]
It's worth noting also that this PR is largely a representation of the reports API _internals_ only, that is, I fully expect the implementation team to build outer layers for the registering and configuring of reports, endpoints, and display mechanisms in EDD.

So please try to keep in mind that this really just represents the first part of the reports overhaul – the guts; none of the existing core reports have been converted to use any of the new APIs (the implementation team will do that). The fact that the core reports still display is merely an indicator that backward compatibility has been taken into account for display purposes.

**Comment by pippinsplugins** [comment]
@DrewAPicture do I need to do anything specific to support date filters? I see the date filters in the existing and new reports (using the example report provided) but they do not function. Is the example missing a key piece or is that a bug?

**Comment by spencerfinnell** [comment]
Noticed some tabs are outputting multiple date selectors. This causes the following JS to fail:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/c3a813cc5021409b295260a8edb761a7bbe9b5b8/assets/js/admin-scripts.js#L992-L1002

The multiple IDs on the page are invalid (technically) and causes only the first instance of the HTML to use the JS. The ID should be switched to a class selector if multiple will appear on the page.

Class selectors are slower but it would require looping through all instances of the ID otherwise, which is probably just as slow.

**Comment by DrewAPicture** [comment]
Just demonstrated the date filter saving state and adjusting a chart endpoint in person for @pippinsplugins  so maybe something weird with his setup isn't working.

@spencerfinnell Noted. Probably can just switch to a class and each it.

**Comment by DrewAPicture** [comment]
> Also I think the previously used .show() and .hide() functions make more sense here as when the items are hidden they are not relevant to screen readers either.
@spencerfinnell If they're UI elements, they're relevant. `display:none` completely hides the elements and unless you notify screen readers when you're showing and hiding elements with JS through something like `wp.speak()` every time, then those visual interactions are pretty much a complete mystery to screen reader users.

**Comment by DrewAPicture** [comment]
Merged #6273 to bring in the entirety of the new Reports API internals  🎉 

New issues for anything that comes up in implementation.

**Comment by DrewAPicture** [comment]
Example report:

![Example report](https://cl.ly/0c3A3t0v290P/Screen%20Shot%202018-05-01%20at%2009.55.36-fullpage.png)

**Comment by spencerfinnell** [comment]
@DrewAPicture 

> If they're UI elements, they're relevant. display:none completely hides the elements and unless you notify screen readers when you're showing and hiding elements with JS through something like wp.a11y.speak() every time, then those visual interactions are pretty much a complete mystery to screen reader users. Describing those fields via an aria-describedby or legend would probably be useful, regardless.

But the fields are being hidden because they are not relevant to the other filters (and cannot be modified by mouse, keyboard, or voice). Having them visible to screen readers when using a range other than "Custom" would cause readers to announce them when they are not needed and are not able to be modified.

I'm not sure the best way to announce when they have appeared -- probably `wp.a11y.speak()` like you said.

**Comment by DrewAPicture** [comment]
## Overview

The Reports API Reboot represents the next higher level of modularization for reports. The entire idea of this reboot is to break the data represented in a "report" into logical chunks, make it possible to _build_ new or rebuild old reports using those chunks, and _refresh_ how those chunks can be visualized

Think of the idea of a new "report" as a way to containerize data points (endpoints) in a structured way. A report contains endpoints, which each contain view definitions, and sometimes those view definitions contain datasets and manifests. Basically speaking, the reports API reboot takes what is currently hard-coded, modularizes it, and sets up a mechanism through which data is retrieved just in time for display.

## Getting Registered

EDD 3.0 introduces the concept of a "registry". Items get added to a registry (in memory) and then can be retrieved globally for various purposes.

And there can be any number of independent registries created. The new Reports API introduces two registries, one each for reports and endpoints that will be consumed by those registered reports, respectively.

Moving forward, it's important to draw a distinction between what we think of as a "reports tab" and a report, because a "reports tab" represents the visualization of a "report" which is now a structured data object. More on that below.

Reports and endpoint registration are handled separately for reasons that will be explained later, but the main thing to consider is that reports and endpoints are added to registries to kill two birds with one stone:
1. Get all of the needed data together in one place for global access
2. Handle error checking and validation on the way in

The reason error checking and validation happens during registration, is that the registry data needs to be in a very specific format when it is later pulled out and built into structured data objects. If there's a problem on the way in, there is a whole bunch of internal logic in place to not only check for errors, but report those exceptions to the debug log (yay making support easier!).

Great pains have been taken to ensure that errors at any level of the API can be logged and tracked down if debug mode is turned on.

## Reports and Endpoints and Views, oh my!

Let's talk a little bit more about terminology for a minute. For the purposes of the new reports API, a "report" is a structured data object representing all of the data that might be displayed with it. An "endpoint" is a structured data object leveraged by a report to display a piece of data. A view defines one or more ways an endpoint can be visualized.

To see this in action, check this [sample plugin](https://gist.github.com/DrewAPicture/69acc0a74af184f11443687802ac89a4).

Here, two reports are registered in the `register_report()` method, each defining endpoints they would like to surface via several different "view groups", i.e. tiles, charts, or tables.

In the `register_endpoint()` method, endpoints are registered. Notice that each endpoint defines views through which that particular data point can be visualized. Each view definition contains its own display and data callbacks.

In comparing the report and endpoint registrations, notice the correlation between the view groups in the 'endpoints' attribute of the report and the view definitions in the 'view' attribute of the endpoint. 'tile' is to 'tiles' as 'chart' is to 'charts' as 'table' is to 'tables'.

Basically, any one endpoint can register view definitions for any valid view type, making the data reusable in multiple contexts and even multiple different reports. You could express earnings data as a tile (single piece of data), a table (data table), and/or a chart (pie/doughnut chart or line/bar graph). An endpoint simply needs to register _at least_ one view definition to be valid.

Reports leverage view groups to determine whether registered endpoints contain compatible view definitions. If an endpoint registers 'tile' and 'table' views and a report calls for that endpoint using the 'charts' group, it's going to fail silently.

## Structured Data

When data in the reports and endpoints registries is later retrieved, API functionality _builds_ that data into structured data objects.

Just as you could conceivably hit a REST endpoint and get back JSON data in the form of a response, Report and Endpoint objects represent data, but in a much richer format than just raw data: the response is a fully-qualified data object decorated with helper methods and error checking.

The API doesn't currently contain actual REST endpoints, but it's built in a way that making that possible in the future would be fairly straightforward. See #6281.

Here is a basic rundown of what happens when a reports tab is loaded

1. A report tab starts to display
2. It calls for a specific, registered report
3. The report is retrieved from the registry and built into a Report object
4. At this time, all endpoints whitelisted for the report are looped through and Endpoint objects are built for each of them, as long as they contain valid view definitions and don't trigger any errors. If one or both conditions are not met, errors are logged to the Report object and that specific Endpoint object is not built.
5. Any whitelisted, valid filters are displayed
6. The report display callback loops through those rich endpoint objects and triggers their display methods
7. At this time, the data callbacks are finally fired, just in time for display – more on this below
8. The report is displayed with all of its endpoints.

If you note in step 7 above, the data callbacks don't get called until the Endpoint object display callbacks are called. This is what makes the new reports API so much faster: All of the data in the registry is static, and all of the data in the Endpoints is static right up until it's time to display it _and then_ it's retrieved just in time.

---

This is part one of a series of abstracts explaining how the new reports API works. More to come.
