### ISSUE TITLE
3.0 Reports: Implementation overview

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6296]
This is the general tracking issue for the reports implementation phase. An issue will be created for each reports tab, and each issue will have the details for that particular tab.

When a specific report has a PR, it will be linked below.

Once a report has been fully tested and merged, please tick its checkbox below.

Reports (tabs) may have:
- Filters
- Tiles
- Charts

**Tabs**
- [x] Overview - Issue #6297 / PR ?
- [x] Products - Issue #6298 / PR ?
- [x] Refunds - Issue #6299 / PR ?
- [x] Payment Gateways - Issue #6300 / PR ?
- [x] Taxes - Issue #6301 / PR ?
- [x] File Downloads - Issue #6302 / PR ?
- [x] Discounts - Issue #6303 / PR ?
- [x] Customers - Issue #6304 / PR ?
- [x] Export - Issue #6305 / PR ?

**Filters**
Filters affect what a report displays. Filter selections will persist, where appropriate.

EDD has the following date filters:
- Today
- Yesterday
- This week
- Last week
- Last 30 days
- This month
- Last month
- This quarter
- Last quarter
- This year
- Last year
- Custom

Some reports will also implement filters for:
- Product and/or product price option selection
- Taxes (with or without)
- Payment gateway
- Discount code

Filter details will be listed on the individual issues.

**Tiles and Charts**
Each tab will have its own set of tiles and charts, where applicable. Details for those will be in the individual issues.

**Comment by sunnyratilal** [comment]
This branch will be based off #6665 as it contains the new Stats class.  The issues for each individual tab will then branch off this issue.

**Comment by sunnyratilal** [comment]
PR opened at #6681.

**Comment by sunnyratilal** [comment]
The majority of the reports are now merged into `release/3.0`.

@JJJ and I will add the Refunds reports once the new APIs are ready.
