### ISSUE TITLE
3.0 Reports: New stats class

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#6665]
We need to introduce a new stats class that uses Carbon to calculate the dates and caches results.

The stats class will be used to calculate the data for the reports to avoid duplication of code.

The new class will also be used to refactor the calculations for the dashboard widget.

Adding the calculations in a single class allows us to keep all the calculations together whilst reusing code rather than duplicating it.  Once the class is complete, it will make the reports implementation significantly easier.

### To-Do
- [x] Order earnings for given time period
- [x] Number of orders for given time period
- [x] Earnings for specific order items
- [x] Total amount saved for a specific discount code
- [x] Number of refunds for a given time period
- [x] Average customer value
- [x] Average refund amount
- [x] Average discount amount
- [x] Sales/refunds/earnings per gateway
- [x] Average value per gateway
- [x] Total tax collected
- [x] Tax collected per location (country/state)
- [x] Average refund time

**Comment by sunnyratilal** [comment]
PR opened at #6666

**Comment by sunnyratilal** [comment]
Class implemented along with methods.

Refund methods will be added once #2721 is done.
